### ISSUE TITLE
Do I need to install libraly?

### ISSUE THREAD

**Issue by NanamiTakayama** [xshellinc/opcv-string-obj#1]
(env) Satone-no-MacBook:opcv-string-obj satoneyamanami$ python compare.py images/
INFO compare.py: 158: images/output/car/0_005.jpg
Traceback (most recent call last):
  File "compare.py", line 169, in <module>
    main(args)
  File "compare.py", line 160, in main
    compare(im_name, args.folder)
  File "compare.py", line 48, in compare
    detector_s = cv2.xfeatures2d.SIFT_create()
AttributeError: 'module' object has no attribute 'xfeatures2d'

**Comment by tectiv3** [comment]
your opencv was built without contrib modules. You need to rebuild it.
